-- Q1 What is the total revenue generated by male vs female?
SELECT Gender, SUM(`Purchase Amount (USD)`) AS revenue
FROM customer_data
GROUP BY Gender;
-- Q2 Which Customer used a discout but still spent more than the average purcahse amount?
SELECT `Customer ID`, `Purchase Amount (USD)`
FROM customer_data
WHERE `Discount Applied` = 'Yes'
AND `Purchase Amount (USD)` > (
    SELECT AVG(`Purchase Amount (USD)`)
    FROM customer_data
);
-- Q3 which are the top 5 product with highest average review rating?
SELECT 
    `Item Purchased`,
    AVG(`Review Rating`) AS avg_review_rating
FROM customer_data
GROUP BY `Item Purchased`
ORDER BY avg_review_rating DESC
LIMIT 5;
-- Q4 campare the average purchase amounts between standard and express shipping
SELECT 
    `Shipping Type`,
    AVG(`Purchase Amount (USD)`) AS avg_purchase_amount
FROM customer_data
WHERE `Shipping Type` IN ('Standard', 'Express')
GROUP BY `Shipping Type`;
-- Q5  Do subcribed customer spend more ? campare average spend and total revenue between subcriber and non subcriber
SELECT 
    `Subscription Status`,
    COUNT(*) AS total_orders,
    AVG(`Purchase Amount (USD)`) AS avg_spend,
    SUM(`Purchase Amount (USD)`) AS total_revenue
FROM customer_data
GROUP BY `Subscription Status`;
-- Q6 which 5 Products have the highest percentage of purchase with discount applied?
SELECT 
    `Item Purchased`,
    COUNT(*) AS total_purchases,
    SUM(CASE WHEN `Discount Applied` = 'Yes' THEN 1 ELSE 0 END) AS discount_purchases,
    (SUM(CASE WHEN `Discount Applied` = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS discount_percentage
FROM customer_data
GROUP BY `Item Purchased`
ORDER BY discount_percentage DESC
LIMIT 5;
-- Q7 Segment customer into new , returning and loyal based on their total number of previous purchases and show the count of each segment
SELECT 
    CASE 
        WHEN `Previous Purchases` = 0 THEN 'New Customer'
        WHEN `Previous Purchases` BETWEEN 1 AND 5 THEN 'Returning Customer'
        ELSE 'Loyal Customer'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer_data
GROUP BY customer_segment;
-- Q8 What are the top 3 most purchased products within each category ?
SELECT Category, `Item Purchased`, total_purchases
FROM (
    SELECT 
        `Category`,
        `Item Purchased`,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER (PARTITION BY `Category` ORDER BY COUNT(*) DESC) AS rank_num
    FROM customer_data
    GROUP BY `Category`, `Item Purchased`
) ranked_products
WHERE rank_num <= 3;
-- Q9  Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    `Subscription Status`,
    COUNT(*) AS repeat_buyers
FROM customer_data
WHERE `Previous Purchases` > 5
GROUP BY `Subscription Status`;
-- Q10 What is the revenue contribution of each age group?
SELECT 
    CASE
        WHEN Age BETWEEN 18 AND 25 THEN 'Young Adult'
        WHEN Age BETWEEN 26 AND 35 THEN 'Adult'
        WHEN Age BETWEEN 36 AND 50 THEN 'Middle-Aged'
        ELSE 'Senior'
    END AS age_group,
    SUM(`Purchase Amount (USD)`) AS total_revenue
FROM customer_data
GROUP BY age_group;
